[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "passman"
version = "0.1.0"
description = "A simple CLI password manager"
readme = "README.md"
requires-python = ">=3.12"

authors = [
    {name = "Tushar"}
]

dependencies = [
    "rich",
]

[project.scripts]
passman = "passman.main:main"

[tool.setuptools.packages.find]
where = ["."]